---

development:
  dialect: sqlite
  database: /tmp/helpdesk_lite_development.sqlite

test:
  dialect: sqlite
  database: /tmp/helpdesk_lite_test.sqlite

production:
  dialect: sqlite
  database: /tmp/helpdesk_lite_production.sqlite